---
- name: 'Provision AMI'
  hosts: default
  vars:
    app_version: 1.0.0
    user: ubuntu

  tasks:
    - name: Add package software-properties-common
      apt:
        name: software-properties-common
        state: latest
        install_recommends: no
        update_cache: yes
      become: true

    - name: Add PHP repository
      shell: add-apt-repository ppa:ondrej/php
      become: true

    - name: Refresh caches
      shell: apt-get update
      become: true

    - name: Install packages
      shell: apt-get --fix-broken install -yf {{ item }}
      with_items:
        - apache2
        - apache2-bin
        - apache2-utils
        - php7.4
        - php7.4-xml
        - php7.4-mbstring
        - php7.4-pdo
        - php7.4-mysql
        - php7.4-intl
        - unzip
      become: true

    - name: Download Composer
      shell: curl -sS https://getcomposer.org/installer -o composer-setup.php

    - name: Install Composer
      shell: php composer-setup.php --install-dir=/usr/local/bin --filename=composer && rm -f composer-setup.php
      become: true

    - name: Remove default Apache file
      file:
        path: /var/www/html/index.html
        state: absent
      become: true

    - name: Extract sources into /var/www/html
      unarchive:
        src: "https://github.com/jeremychauvet/template-symfony/archive/refs/tags/{{ app_version }}.zip"
        dest: /tmp/
        remote_src: yes
        owner: "{{ user }}"

    - name: Deploy sources to /var/www/html
      copy:
        src: "/tmp/template-symfony-{{ app_version }}/web/"
        dest: /var/www/html
        remote_src: yes
      become: true

    - name: Create cache folder to avoid create errors
      file:
        path: /var/www/html/var/cache
        state: directory
        recurse: yes
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'
      become: true

    - name: Download and installs all libs and dependencies outlined in the composer.lock
      shell: cd /var/www/html && composer install
      become: true

    - name: Change group and permissions
      shell: chmod -R 777 "{{ item }}" && chown -R ubuntu:ubuntu "{{ item }}"
      with_items:
        - /var/www/html
        - /etc/apache2/sites-enabled
      become: true
