---
- name: 'Provision AMI'
  hosts: localhost
  vars:
    app_version: 1.0.0
    user: ubuntu

  tasks:
    - name: Add package software-properties-common
      apt:
        name: software-properties-common
        state: latest
        install_recommends: no
        update_cache: yes
      become: true

    - name: Add PHP repository
      command: add-apt-repository ppa:ondrej/php

    - name: Refresh caches
      command: apt-get update

    - name: Install packages
      command: apt-get --fix-broken install -yf {{ item }}
      with_items:
        - apache2
        - apache2-bin
        - apache2-utils
        - php7.4
        - php7.4-xml
        - php7.4-mbstring
        - php7.4-pdo
        - php7.4-mysql
        - php7.4-intl
        - unzip

    - name: Download Composer
      command: curl -sS https://getcomposer.org/installer -o composer-setup.php

    - name: Install Composer
      command: php composer-setup.php --install-dir=/usr/local/bin --filename=composer && rm -f composer-setup.php

    - name: Remove default Apache file
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Extract sources into /var/www/html
      unarchive:
        src: "https://github.com/jeremychauvet/template-symfony/archive/refs/tags/{{ app_version }}.zip"
        dest: /tmp/
        remote_src: yes
        owner: "{{ user }}"

    - name: Deploy sources to /var/www/html
      copy:
        src: "/tmp/template-symfony-{{ app_version }}/web/"
        dest: /var/www/html

    - name: Change folder ownership, group and permissions
      file:
        path: /var/www/html
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'
        recurse: yes

    - name: Create default .env
      file:
        path: /var/www/html/.env
        state: touch
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'

    - name: Create cache folder to avoid create errors
      file:
        path: /var/www/html/var/cache
        state: directory
        recurse: yes
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'

    - name: Download and installs all libs and dependencies outlined in the composer.lock
      composer:
        command: install
        working_dir: /var/www/html
